// <auto-generated />
using System;
using Endfield.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Endfield.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303133748_AddVideoRefreshFields")]
    partial class AddVideoRefreshFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Endfield.Api.Entities.BilibiliVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bvid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bvid")
                        .HasComment("B站视频唯一标识");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment")
                        .HasComment("备注信息");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("cover")
                        .HasComment("视频封面URL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by")
                        .HasComment("创建人ID");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_name")
                        .HasComment("创建人名称");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("视频简介");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration")
                        .HasComment("视频时长（秒）");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否删除（软删除标记）");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastRefreshTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("like_count")
                        .HasComment("点赞数");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("owner_name")
                        .HasComment("UP主名称");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publish_time")
                        .HasComment("发布时间");

                    b.Property<int>("RefreshRetryCount")
                        .HasColumnType("int");

                    b.Property<int>("RefreshStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title")
                        .HasComment("视频标题");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("最后修改时间");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by")
                        .HasComment("最后修改人ID");

                    b.Property<string>("UpdatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_name")
                        .HasComment("最后修改人名称");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("url")
                        .HasComment("视频链接");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint")
                        .HasColumnName("view_count")
                        .HasComment("播放量");

                    b.HasKey("Id");

                    b.HasIndex("Bvid")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.ToTable("bilibili_videos", null, t =>
                        {
                            t.HasComment("B站视频信息表");
                        });
                });

            modelBuilder.Entity("Endfield.Api.Entities.RequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("api_name")
                        .HasComment("接口名称（Controller/Action格式）");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("client_ip")
                        .HasComment("客户端IP地址");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment")
                        .HasComment("备注信息");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("correlation_id")
                        .HasComment("请求追踪ID，用于关联一次请求的完整链路");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by")
                        .HasComment("创建人ID");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_name")
                        .HasComment("创建人名称");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms")
                        .HasComment("执行耗时（毫秒）");

                    b.Property<string>("Environment")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("environment")
                        .HasComment("运行环境（Development/Production等）");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("exception_message")
                        .HasComment("异常消息");

                    b.Property<string>("ExceptionStackTrace")
                        .HasColumnType("text")
                        .HasColumnName("exception_stack_trace")
                        .HasComment("异常堆栈信息");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("exception_type")
                        .HasComment("异常类型");

                    b.Property<string>("ExtraData")
                        .HasColumnType("text")
                        .HasColumnName("extra_data")
                        .HasComment("额外数据（JSON格式，用于存储自定义字段）");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否删除（软删除标记）");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_success")
                        .HasComment("是否成功（200-399为成功）");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("log_level")
                        .HasComment("日志级别（Information/Warning/Error等）");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_name")
                        .HasComment("机器名/主机名");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("message")
                        .HasComment("日志消息");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("query_string")
                        .HasComment("查询字符串");

                    b.Property<string>("RequestBody")
                        .HasColumnType("longtext")
                        .HasColumnName("request_body")
                        .HasComment("请求入参（JSON格式，敏感信息已脱敏）");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text")
                        .HasColumnName("request_headers")
                        .HasComment("请求头（JSON格式）");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("request_method")
                        .HasComment("请求方法（GET/POST/PUT/DELETE等）");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("request_path")
                        .HasComment("请求路径");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_time")
                        .HasComment("请求时间（UTC）");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("longtext")
                        .HasColumnName("response_body")
                        .HasComment("返回结果（JSON格式）");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("text")
                        .HasColumnName("response_headers")
                        .HasComment("响应头（JSON格式）");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("response_time")
                        .HasComment("响应时间（UTC）");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code")
                        .HasComment("HTTP状态码");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("最后修改时间");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by")
                        .HasComment("最后修改人ID");

                    b.Property<string>("UpdatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_name")
                        .HasComment("最后修改人名称");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("user_agent")
                        .HasComment("用户代理（浏览器/客户端信息）");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasComment("用户ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.HasIndex("ApiName");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("RequestTime");

                    b.HasIndex("StatusCode");

                    b.HasIndex("UserId");

                    b.ToTable("request_logs", null, t =>
                        {
                            t.HasComment("请求日志表");
                        });
                });

            modelBuilder.Entity("Endfield.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("用户ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment")
                        .HasComment("备注信息");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by")
                        .HasComment("创建人ID");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_name")
                        .HasComment("创建人名称");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email")
                        .HasComment("邮箱地址");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasComment("是否启用");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否删除（软删除标记）");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickname")
                        .HasComment("昵称");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("password")
                        .HasComment("密码（加密存储）");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("最后修改时间");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by")
                        .HasComment("最后修改人ID");

                    b.Property<string>("UpdatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_name")
                        .HasComment("最后修改人名称");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username")
                        .HasComment("用户名（登录名）");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("用户表");
                        });
                });

            modelBuilder.Entity("Endfield.Api.Entities.VideoTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code")
                        .HasComment("标签编码（唯一标识）");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment")
                        .HasComment("备注信息");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by")
                        .HasComment("创建人ID");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_name")
                        .HasComment("创建人名称");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description")
                        .HasComment("标签描述");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否删除（软删除标记）");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name")
                        .HasComment("标签名称");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order")
                        .HasComment("排序序号");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("最后修改时间");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by")
                        .HasComment("最后修改人ID");

                    b.Property<string>("UpdatedName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_name")
                        .HasComment("最后修改人名称");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SortOrder");

                    b.ToTable("video_tags", null, t =>
                        {
                            t.HasComment("视频标签表");
                        });
                });

            modelBuilder.Entity("Endfield.Api.Entities.VideoTagMapping", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id")
                        .HasComment("视频ID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id")
                        .HasComment("标签ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.HasKey("VideoId", "TagId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TagId");

                    b.ToTable("video_tag_mappings", null, t =>
                        {
                            t.HasComment("视频标签关联表");
                        });
                });

            modelBuilder.Entity("Endfield.Api.Entities.VideoTagMapping", b =>
                {
                    b.HasOne("Endfield.Api.Entities.VideoTag", "Tag")
                        .WithMany("VideoTagMappings")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Endfield.Api.Entities.BilibiliVideo", "Video")
                        .WithMany("VideoTagMappings")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Endfield.Api.Entities.BilibiliVideo", b =>
                {
                    b.Navigation("VideoTagMappings");
                });

            modelBuilder.Entity("Endfield.Api.Entities.VideoTag", b =>
                {
                    b.Navigation("VideoTagMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
